version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - sloglint
    # - fieldalignment
    # - depguard
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    # - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    # - gocyclo
    # - gomnd
    # - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: -1 # the number of lines (code + empty lines) is not a right metric and leads to code without empty line or one-liner.
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      settings:
        hugeParam:
          sizeThreshold: 300
    gocyclo:
      min-complexity: 15
    govet:
      enable:
        - shadow
    lll:
      line-length: 1000
    misspell:
      locale: US
    nolintlint:
      allow-unused: false # report any unused nolint directives
      require-explanation: false # don't require an explanation for nolint directives
      require-specific: false # don't require nolint directives to be specific about which linter is being skipped
    revive:
      rules:
        - name: unexported-return
          disabled: true
        - name: unused-parameter
    sloglint:
      kv-only: true
      attr-only: false
      # context: true
      static-msg: false
      no-raw-keys: false
      key-naming-case: snake
      args-on-sep-lines: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gomnd

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'

  # don't enable:
  # - asciicheck
  # - scopelint
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - interfacer
  # - maligned
  # - nestif
  # - prealloc
  # - testpackage
  # - wsl

run:
  timeout: 5m
